### PR TITLE
added new files

### PR DESCRIPTION
**Pull request by royaleconqueso**

### CODE REVIEW

**Comment by royaleconqueso** [comment]
Thanks for the help. This is my first merge request, so I see how i did it wrong before, and I think I did it right this time. please let me know. Thanks!

**Comment by martinbjeldbak** [comment]
@brock6 there are just a couple of conflicts due to merging another PR. Once fixed, this one looks good to go! Youve done everything right 👍  thanks again!

**Comment by martinbjeldbak** [comment]
@brock6 is this PR still relevant? It looks like the same 3 themes have just been added in #14.

**Comment by martinbjeldbak** [comment]
Closing this one as it is a duplicate

**Pull request closed without merging**
